import type { AgentInfo, DayActivity, Lead, LogEntry } from './types'

function isoDaysAgo(days: number, hour = 10): string {
  const d = new Date()
  d.setDate(d.getDate() - days)
  d.setHours(hour, 15, 0, 0)
  return d.toISOString()
}

export const INITIAL_AGENTS: AgentInfo[] = [
  {
    name: 'Orchestrator',
    role: 'Coordina pipeline, prioriza y escala HITL',
    status: 'idle',
  },
  {
    name: 'Scout',
    role: 'Descubre pymes sin web o desactualizada',
    status: 'idle',
  },
  {
    name: 'Diagnoser',
    role: 'Diagnóstico comercial + pitch ES-CL',
    status: 'idle',
  },
  {
    name: 'Builder',
    role: 'Genera landing HTML responsive',
    status: 'idle',
  },
  {
    name: 'Filmer',
    role: 'Storyboard / video vertical 10–15s',
    status: 'idle',
  },
  {
    name: 'Checker',
    role: 'Calidad + Ley 21.719 + anti-spam',
    status: 'idle',
  },
  {
    name: 'Pitcher',
    role: 'Prepara y simula envíos (sin Checker no envía)',
    status: 'idle',
  },
  {
    name: 'Mobile',
    role: 'Respuestas cortas y agenda Calendly',
    status: 'idle',
  },
]

export const INITIAL_LEADS: Lead[] = [
  {
    id: 'lead_demo_01',
    business: 'Clínica Dental Los Robles',
    category: 'Salud',
    city: 'Santiago',
    commune: 'Las Condes',
    hasWebsite: false,
    rating: 4.7,
    reviews: 86,
    status: 'nuevo',
    estimatedValueClp: 380_000,
    highValue: false,
    channels: ['instagram_dm', 'email'],
    contactHint: 'IG @clinicarobles (público)',
    createdAt: isoDaysAgo(6),
    updatedAt: isoDaysAgo(6),
  },
  {
    id: 'lead_demo_02',
    business: 'Studio Belleza Ñuñoa',
    category: 'Belleza',
    city: 'Santiago',
    commune: 'Ñuñoa',
    hasWebsite: true,
    websiteYear: 2018,
    rating: 4.5,
    reviews: 124,
    status: 'diagnosticado',
    estimatedValueClp: 320_000,
    diagnosis:
      'Web del 2018 sin móvil ni CTA. Competencia en Plaza Ñuñoa ya captura reservas online. Oportunidad: landing de captación + WhatsApp business con opt-in.',
    highValue: false,
    channels: ['instagram_dm', 'email', 'linkedin'],
    contactHint: 'email de contacto en Google Maps',
    createdAt: isoDaysAgo(5),
    updatedAt: isoDaysAgo(4, 14),
  },
  {
    id: 'lead_demo_03',
    business: 'Taller Automotriz Maipú Express',
    category: 'Automotriz',
    city: 'Santiago',
    commune: 'Maipú',
    hasWebsite: false,
    rating: 4.3,
    reviews: 210,
    status: 'landing',
    estimatedValueClp: 290_000,
    diagnosis: 'Sin web; alto volumen de reseñas. Landing de servicios + cotización rápida.',
    pitch:
      'Hola, vi que Taller Maipú Express tiene excelente reputación en Maps pero aún no tiene web. Te armé un borrador de landing para captar cotizaciones. ¿Te lo muestro 10 min? Responde STOP si no te interesa.',
    highValue: false,
    channels: ['email', 'linkedin'],
    createdAt: isoDaysAgo(4),
    updatedAt: isoDaysAgo(3, 11),
  },
  {
    id: 'lead_demo_04',
    business: 'Café Barrio Italia',
    category: 'Gastronomía',
    city: 'Santiago',
    commune: 'Providencia',
    hasWebsite: true,
    websiteYear: 2019,
    rating: 4.6,
    reviews: 340,
    status: 'video',
    estimatedValueClp: 350_000,
    diagnosis: 'Web estática sin menú ni reservas. Ideal reels + landing de menú del día.',
    pitch:
      'Hola equipo de Café Barrio Italia: preparé un storyboard de 12s y una landing para menú y reservas. ¿Coordinamos una llamada corta? Escribe STOP para no recibir más mensajes.',
    highValue: false,
    channels: ['instagram_dm', 'email'],
    createdAt: isoDaysAgo(3),
    updatedAt: isoDaysAgo(2, 16),
  },
  {
    id: 'lead_demo_05',
    business: 'FitLife Gym Viña',
    category: 'Fitness',
    city: 'Viña del Mar',
    commune: 'Viña del Mar',
    hasWebsite: false,
    rating: 4.4,
    reviews: 95,
    status: 'pitch_listo',
    estimatedValueClp: 410_000,
    diagnosis: 'Sin presencia web; temporada turística. Landing de planes + prueba gratis.',
    pitch:
      'Hola FitLife Gym Viña: armé una landing de planes y una pieza vertical 12s para IG. Te la muestro sin compromiso. Responde STOP si prefieres no seguir conversando.',
    highValue: false,
    channels: ['instagram_dm', 'email', 'linkedin'],
    createdAt: isoDaysAgo(2),
    updatedAt: isoDaysAgo(1, 9),
  },
  {
    id: 'lead_demo_06',
    business: 'Estudio Jurídico Costanera',
    category: 'Legal',
    city: 'Concepción',
    commune: 'Concepción',
    hasWebsite: true,
    websiteYear: 2016,
    rating: 4.8,
    reviews: 62,
    status: 'enviado',
    estimatedValueClp: 450_000,
    diagnosis: 'Web desactualizada; oportunidad B2B con LinkedIn + landing de áreas de práctica.',
    pitch:
      'Estimados de Estudio Jurídico Costanera: preparé una propuesta de landing profesional con captación de consultas. ¿Agendamos 15 min? Indique STOP para opt-out.',
    highValue: false,
    channels: ['linkedin', 'email'],
    createdAt: isoDaysAgo(7),
    updatedAt: isoDaysAgo(1, 18),
  },
  {
    id: 'lead_demo_07',
    business: 'Academia Temuco English',
    category: 'Educación',
    city: 'Temuco',
    commune: 'Temuco',
    hasWebsite: false,
    rating: 4.9,
    reviews: 48,
    status: 'respondio',
    estimatedValueClp: 360_000,
    diagnosis: 'Sin web; alto rating. Landing de cursos + formulario de matrícula.',
    pitch: 'Pitch enviado con opt-out. Lead respondió pidiendo demo.',
    highValue: false,
    channels: ['email', 'instagram_dm'],
    createdAt: isoDaysAgo(8),
    updatedAt: isoDaysAgo(0, 8),
  },
  {
    id: 'lead_demo_08',
    business: 'Retail Hogar del Sur',
    category: 'Retail',
    city: 'Santiago',
    commune: 'Providencia',
    hasWebsite: true,
    websiteYear: 2015,
    rating: 4.2,
    reviews: 180,
    status: 'agendado',
    estimatedValueClp: 420_000,
    diagnosis: 'Catálogo online obsoleto. Landing de campaña + WhatsApp con consentimiento.',
    pitch: 'Demo agendada vía Calendly.',
    highValue: false,
    channels: ['email', 'linkedin'],
    createdAt: isoDaysAgo(10),
    updatedAt: isoDaysAgo(0, 12),
  },
  {
    id: 'lead_demo_09',
    business: 'Holding Salud Andes Premium',
    category: 'Salud',
    city: 'Santiago',
    commune: 'Las Condes',
    hasWebsite: true,
    websiteYear: 2017,
    rating: 4.6,
    reviews: 410,
    status: 'revision',
    estimatedValueClp: 3_250_000,
    diagnosis:
      'Red de clínicas multi-sede. Proyecto multi-landing + CRM. Valor estimado supera umbral HITL (2.8M CLP).',
    pitch:
      'Propuesta multi-sede (borrador). Requiere aprobación humana antes de cualquier envío.',
    reason: 'Deal 3.250.000 CLP → revisión manual (HITL ~3.000 USD)',
    highValue: true,
    channels: ['linkedin', 'email'],
    contactHint: 'solo contactos corporativos públicos',
    createdAt: isoDaysAgo(2),
    updatedAt: isoDaysAgo(0, 15),
  },
  {
    id: 'lead_demo_10',
    business: 'Minimarket Don Pedro',
    category: 'Retail',
    city: 'Santiago',
    commune: 'Maipú',
    hasWebsite: false,
    rating: 4.1,
    reviews: 33,
    status: 'cerrado',
    estimatedValueClp: 250_000,
    diagnosis: 'Bajo ticket digital; cerró por no prioridad.',
    highValue: false,
    channels: ['email'],
    createdAt: isoDaysAgo(12),
    updatedAt: isoDaysAgo(5),
  },
]

export const INITIAL_LOGS: LogEntry[] = [
  {
    id: 'log_1',
    ts: isoDaysAgo(0, 9),
    agent: 'Orchestrator',
    message: 'Sistema en línea · pipeline listo (modo demo)',
    level: 'success',
  },
  {
    id: 'log_2',
    ts: isoDaysAgo(0, 9),
    agent: 'Scout',
    message: 'Semilla: 10 leads mock Chile cargados en store',
    level: 'info',
  },
  {
    id: 'log_3',
    ts: isoDaysAgo(0, 10),
    agent: 'Checker',
    message: 'Reglas Ley 21.719 activas · opt-out obligatorio en pitch',
    level: 'info',
  },
  {
    id: 'log_4',
    ts: isoDaysAgo(0, 11),
    agent: 'Pitcher',
    message: 'Pitch listo: FitLife Gym Viña (pitch_listo)',
    level: 'info',
  },
  {
    id: 'log_5',
    ts: isoDaysAgo(0, 12),
    agent: 'Orchestrator',
    message: 'Holding Salud Andes Premium → revision (3.25M CLP HITL)',
    level: 'warn',
  },
  {
    id: 'log_6',
    ts: isoDaysAgo(0, 14),
    agent: 'Mobile',
    message: 'Academia Temuco English respondió · sugerir agenda Calendly',
    level: 'success',
  },
]

export const INITIAL_ACTIVITY: DayActivity[] = [
  { day: 'Lun', leads: 4, mensajes: 6, respuestas: 1 },
  { day: 'Mar', leads: 3, mensajes: 5, respuestas: 0 },
  { day: 'Mié', leads: 5, mensajes: 8, respuestas: 2 },
  { day: 'Jue', leads: 2, mensajes: 4, respuestas: 1 },
  { day: 'Vie', leads: 6, mensajes: 9, respuestas: 2 },
  { day: 'Sáb', leads: 1, mensajes: 2, respuestas: 0 },
  { day: 'Dom', leads: 2, mensajes: 3, respuestas: 1 },
]

export const ORCHESTRATOR_PROMPT = `Eres el Orchestrator del Agente IA Autónomo (agencia unipersonal, Chile).

Objetivo: vender landings a pymes locales con flujo Scout → Diagnoser → Builder → Filmer → Checker → Pitcher → Mobile.

Reglas:
- Estado compartido en filesystem/JSON (no solo RAM).
- Español chileno; precio paquete 250.000–450.000 CLP.
- HITL si deal ≥ 2.800.000 CLP (~3.000 USD) o tasa respuesta < 12%.
- Canales prioritarios: IG DM, email, LinkedIn. WhatsApp: no cold agresivo.
- Checker debe aprobar (opt-out STOP, sin datos inventados) antes de cualquier envío.
- Pitcher nunca envía sin aprobación del Checker.
- Cumplir Ley 21.719 (protección de datos personales) y anti-spam.

Prioriza leads sin web o con web >5 años. Escala a humano en revision; no inventes teléfonos ni emails privados.`

export const SCOUT_POOL: Array<Omit<Lead, 'id' | 'createdAt' | 'updatedAt' | 'status' | 'highValue'>> =
  [
    {
      business: 'Peluquería Estilo Centro',
      category: 'Belleza',
      city: 'Santiago',
      commune: 'Providencia',
      hasWebsite: false,
      rating: 4.4,
      reviews: 57,
      estimatedValueClp: 310_000,
      channels: ['instagram_dm', 'email'],
      contactHint: 'IG público',
    },
    {
      business: 'Kinesiología Vital Ñuñoa',
      category: 'Salud',
      city: 'Santiago',
      commune: 'Ñuñoa',
      hasWebsite: true,
      websiteYear: 2017,
      rating: 4.8,
      reviews: 91,
      estimatedValueClp: 390_000,
      channels: ['email', 'linkedin'],
    },
    {
      business: 'Repuestos Valpo Norte',
      category: 'Automotriz',
      city: 'Valparaíso',
      commune: 'Valparaíso',
      hasWebsite: false,
      rating: 4.2,
      reviews: 140,
      estimatedValueClp: 280_000,
      channels: ['email'],
    },
    {
      business: 'Yoga Mar Concepción',
      category: 'Fitness',
      city: 'Concepción',
      commune: 'Concepción',
      hasWebsite: false,
      rating: 4.9,
      reviews: 44,
      estimatedValueClp: 340_000,
      channels: ['instagram_dm', 'email'],
    },
    {
      business: 'Librería Escolar Temuco',
      category: 'Educación',
      city: 'Temuco',
      commune: 'Temuco',
      hasWebsite: true,
      websiteYear: 2014,
      rating: 4.3,
      reviews: 28,
      estimatedValueClp: 270_000,
      channels: ['email', 'linkedin'],
    },
    {
      business: 'Sushi del Puerto',
      category: 'Gastronomía',
      city: 'Viña del Mar',
      commune: 'Viña del Mar',
      hasWebsite: false,
      rating: 4.5,
      reviews: 220,
      estimatedValueClp: 360_000,
      channels: ['instagram_dm', 'email'],
    },
    {
      business: 'Abogados del Maule',
      category: 'Legal',
      city: 'Santiago',
      commune: 'Las Condes',
      hasWebsite: true,
      websiteYear: 2016,
      rating: 4.7,
      reviews: 39,
      estimatedValueClp: 430_000,
      channels: ['linkedin', 'email'],
    },
  ]
